### ISSUE TITLE
Workflows-Group4-Intro

### ISSUE THREAD

**Issue by alex-maletskyi** [HYF-Class21/workflows-group4-intro#2]
- [x] [Class 21 Group 4 Intro Repo](https://github.com/HYF-Class21/workflows-group4-intro)
- [x] [Alex's bio commit](https://github.com/HYF-Class21/workflows-group4-intro/pull/4/commits/9b5c372b10140c58047c62f20e4729976c81c8eb)
- [x] [Arseniia's bio commit](https://github.com/HYF-Class21/workflows-group4-intro/pull/3/commits/81dfdd924033656c8036714fa80a0286b23604a7)
- [x] [Addi's bio commit](https://github.com/HYF-Class21/workflows-group4-intro/pull/5/commits/64dbbba00d214935fffb0b37973a703fd58a3dc1)
- [x] [Readme file commit](https://github.com/HYF-Class21/workflows-group4-intro/pull/9/commits/c767defc40e82a3a77870e98ecdc6e1fd6135d7c)
- [x] a nice README
- [x] one well-named file per person
- [x] [Alex's PR](https://github.com/HYF-Class21/workflows-group4-intro/pull/4)
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code
- [x] [Arseniia's PR](https://github.com/HYF-Class21/workflows-group4-intro/pull/3)
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code
- [x] [Addi's PR](https://github.com/HYF-Class21/workflows-group4-intro/pull/5)
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code

**Comment by sammou00** [comment]
@AddiAlomoush @alex-maletskyi @ArseniiaDamaksina  Why the group issue is here and not in the home `repo`?

Check group 1 
[Group 1 ](https://github.com/HYF-Class21/workflows-group1-intro/issues)
