### ISSUE TITLE
Added Addi's bio

### ISSUE THREAD

**Issue by AddiAlomoush** [HYF-Class21/workflows-group4-intro#6]
- [x] Cloned the repo.
- [x] Installed npm packages.
- [x] Created a new branch `AddiA` and started working on it.
- [x] Created a file `addi.md` and wrote my bio there.
- [x] Used `git add .` command to add the new file.
- [x] Ran all check commands.
- [x] Commit my work.
- [x] Pushed my work and created PR.

**Comment by sammou00** [comment]
@AddiAlomoush  Why the issue is still opens and you merged your `PR`

**Comment by AddiAlomoush** [comment]
@samirm00 sorry ... I will close it now
